//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalBuild.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class calEntities : DbContext
    {
        public calEntities()
            : base("name=calEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventSlot> EventSlots { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Org> Orgs { get; set; }
        public virtual DbSet<OrgUser> OrgUsers { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<UserEvent> UserEvents { get; set; }
        public virtual DbSet<WaitList> WaitLists { get; set; }
    }
}
